name: astroufcg
channels:
  - conda-forge
dependencies:
  - python=3.12
  - astropy=7.1.0
  - astroquery=0.4.10
  - colour-science=0.4.6
  - geopy=2.4.1
  - ipykernel=6.29.5
  - ipywidgets=8.1.7
  - jupyterlab_widgets=3.0.15
  - markdown-it-py=3.0.0
  - matplotlib=3.10.3
  - mdit-py-plugins=0.4.2
  - mystmd=1.5.0
  - numpy=2.3
  - osmnx=2.0.4
  - pandas=2.3.0
  - pip=25.1.1
  - pydata-sphinx-theme=0.16.1
  - pyvista=0.45.2
  - rich=14.0.0
  - scipy=1.16.0
  - skyfield=1.53
  - sphinx-autodoc2
  - sphinx-copybutton
  - sphinx-design
  - sphinx-togglebutton
  - sphinxcontrib-mermaid
  - pip:
      - trame-jupyter-extension
      - vtk-osmesa
